
[spec]

; Format and options of this spec file:
options = "+Freeciv-2.5-spec"

[info]

artists = "
   feler404
"

[extra]
sprites =
	{	"tag", "file"
		"b.aqueduct", "buildings/aqueduct"
		"b.bank", "buildings/bank"
		"b.barber_shop", "buildings/barber_shop"
		"b.barracks_i", "buildings/barracks_i"
		"b.barracks_ii", "buildings/barracks_ii"
		"b.barracks_iii", "buildings/barracks_iii"
		"b.barracks_iii", "buildings/barracks_iii"
		"b.butcher1", "buildings/butcher1"
		"b.capitalization", "buildings/capitalization"
		"b.cathedral", "buildings/cathedral"
		"b.cavalry_school", "buildings/cavalry_school"
		"b.city_walls", "buildings/city_walls"
		"b.climate_studies_academy", "buildings/climate_studies_academy"
		"b.coastal_defense", "buildings/coastal_defense"
		"b.colosseum", "buildings/colosseum"
		"b.courthouse", "buildings/courthouse"
		"b.culinary_arts", "buildings/culinary_arts"
		"b.draft_board", "buildings/draft_board"
		"b.environment_agency", "buildings/environment_agency"
		"b.farmers_market", "buildings/farmers_market"
		"b.forest_management", "buildings/forest_management"
		"b.grail_component", "buildings/grail_component"
		"b.granary", "buildings/granary"
		"b.guesthouse", "buildings/guesthouse"
		"b.harbor", "buildings/harbor"
		"b.hospital", "buildings/hospital"
		"b.hydro_plant", "buildings/hydro_plant"
		"b.medieval_kitchen", "buildings/medieval_kitchen"
		"b.library", "buildings/library"
		"b.maltese_cross", "buildings/maltese_cross"
		"b.manor", "buildings/manor"
		"b.marketplace", "buildings/marketplace"
		"b.medieval_well", "buildings/medieval_well"
		"b.military_academy", "buildings/military_academy"
		"b.palace", "buildings/palace"
		"b.printing_press", "buildings/printing_press"
		"b.research_lab", "buildings/research_lab"
		"b.sawmill", "buildings/sawmill"
		"b.septic_tank", "buildings/septic_tank"
		"b.sewer_system", "buildings/sewer_system"
		"b.smithing", "buildings/smithing"
		"b.supermarket", "buildings/supermarket"
		"b.temple", "buildings/temple"
		"b.textile_mill", "buildings/textile_mill"
		"b.university", "buildings/university"
		"b.windmill", "buildings/windmill"
		"b.windpump", "buildings/windpump"
		"b.wooden_crane", "buildings/wooden_crane"
		"b.carruca", "buildings/carruca"
		"b.cathedral", "buildings/cathedral"
		"b.courthouse", "buildings/courthouse"
		"b.foundry", "buildings/foundry"
		"b.hydro_plant", "buildings/hydro_plant"
		"b.manor", "buildings/manor"
		"b.medical_research", "buildings/medical_research"
		"b.milling", "buildings/milling"
		"b.prayer",	"buildings/prayer"
		"b.printing_press", "buildings/printing_press"
		"b.sacred_geometry", "buildings/sacred_geometry"
		"b.sewer_system", "buildings/sewer_system"
		"b.sheriffs_office", "buildings/sheriffs_office"
		"b.university", "buildings/university"
	}
