[spec]
options = "+Freeciv-2.5-spec"
[info]
artists = "
Jeff Strickland
"

[file]
gfx = "misc/techs"
[grid_main]
x_top_left = 0
y_top_left = 0
dx = 48
dy = 48
pixel_border = 0
tiles = { "row", "column","tag"
  0, 0, "a.advanced_archery"
  0, 1, "a.alphabet"
  0, 2, "a.amphibious_warfare"
  0, 3, "a.astronomy"
  0, 4, "a.theory_of_impetus"
  0, 5, "a.scientific_method"
  0, 6, "a.banking"
  0, 7, "a.bridge_building"
  0, 8, "a.bronze_working"
  0, 9, "a.ceremonial_burial"
;
  1, 0, "a.chemistry"
  1, 1, "a.chivalry"
  1, 2, "a.code_of_laws"
  1, 3, "a.combined_arms"
  1, 4, "a.ordnance"
  1, 5, "a.collectivism"
  1, 6, "a.medical research"
  1, 7, "a.conscription"
  1, 8, "a.construction"
  1, 9, "a.currency"
;
  2, 0, "a.democracy"
  2, 1, "a.economics"
  2, 2, "a.artesian_drill"
  2, 3, "a.windpump"
  2, 4, "a.engineering"
  2, 5, "a.espionage"
  2, 6, "a.explosives"
  2, 7, "a.feudalism"
  2, 8, "a.artillery"
  2, 9, "a.hydro_power"
;
  3, 0, "a.phlebotomy" ; formerly genetic engineering
  3, 1, "a.guerilla_warfare"
  3, 2, "a.gunpowder"
  3, 3, "a.horseback_riding"
  3, 4, "a.milling"
  3, 5, "a.invention"
  3, 6, "a.iron_working"
  3, 7, "a.die_casting"
  3, 8, "a.cavalry"
  3, 9, "a.leadership"
;
  4, 0, "a.literacy"
  4, 1, "a.machine_tools"
  4, 2, "a.magnetism"
  4, 3, "a.map_making"
  4, 4, "a.masonry"
  4, 5, "a.alchemy"
  4, 6, "a.mathematics"
  4, 7, "a.medicine"
  4, 8, "a.metallurgy"
  4, 9, "a.simple_machines"
;  
  5, 0, "a.mobile_warfare"
  5, 1, "a.monarchy"
  5, 2, "a.monotheism"
  5, 3, "a.mysticism"
  5, 4, "a.navigation"
  5, 5, "a.agriculture"
  5, 6, "a.nuclear_power"
  5, 7, "a.philosophy"
  5, 8, "a.physics"
  5, 9, "a.movable_type"
;  
  6, 0, "a.polytheism"
  6, 1, "a.pottery"
  6, 2, "a.admin"
  6, 3, "a.imp_road"
  6, 4, "a.recycling"
  6, 5, "a.enlightenment"
  6, 6, "a.yakhchal"
  6, 7, "a.templar"
  6, 8, "a.rocketry"
  6, 9, "a.sanitation"
;  
  7, 0, "a.seafaring"
  7, 1, "a.qanat"
  7, 2, "a.stealth"
  7, 3, "a.carruca"
  7, 4, "a.steel"
  7, 5, "a.pilgrimage"
  7, 6, "a.tactics"
  7, 7, "a.guilds"
  7, 8, "a.theology"
  7, 9, "a.theory_of_gravity"
;  
  8, 0, "a.the_republic"
  8, 1, "a.the_wheel"
  8, 2, "a.trade"
  8, 3, "a.university"
  8, 4, "a.warrior_code"
  8, 5, "a.writing"
  8, 6, "a.grail_search"
  8, 7, "a.fundamentalism"
  8, 8, "a.freemasonry"
  8, 9, "a.class_mech"
;
  9, 0, "a.sere" ; survivability
  9, 1, "a.global_warming" ; climate_analysis
  9, 2, "a.forestry"
  9, 3, "a.nutrition"
  9, 4, "a.medieval_stove"
  9, 5, "a.recipe_book"
  9, 6, "a.biochemistry"
  9, 7, "a.biology"
  9, 8, "a.battlefield_medicine"
  9, 9, "a.order_of_the_red_cross"
;
 10, 0, "a.order_of_malta"
 10, 1, "a.order_of_the_temple"
 10, 2, "a.environmentalism"
 10, 3, "a.solid_waste"
 10, 4, "a.grail.research"
 10, 5, "a.grail_security"
 10, 6, "a.animal_husbandry"
 10, 7, "a.agronomy"
 10, 8, "a.christianity"
 10, 9, "a.arched_saddle"
}
